.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ASTMA" "1" "March 2011" "" ""
.
.SH "SYNOPSIS"
AsTMa= is part of the AsTMa* language family which was designed to facilitate authoring, but also constraining and querying topic maps\.
.
.SH "Conventions"
The keywords \fBMUST,\fR \fBMUST NOT,\fR \fBREQUIRED,\fR \fBSHALL,\fR \fBSHALL NOT,\fR \fBSHOULD,\fR \fBSHOULD NOT,\fR \fBRECOMMEND,\fR \fBMAY,\fR and \fBOPTIONAL\fR will be used in this document as defined in RFC 2119\.
.
.SH "Syntax"
\fB\e\fR At the very end of a line n indicates that the followup line n+1 extends line n\.
.
.P
\fB~\fR lines can be split\. If a \fB~\fR has to appear in the text, then it has to be stuffed as \fB~~\fR\.
.
.P
Suggested predefined inline association templates \fIhttp://astma\.it\.bond\.edu\.au/astma=\-spec\-xtm\.dbk?section=13\fR
