.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BASH" "1" "July 2011" "" ""
.
.SH "NAME"
\fBbash\fR \- key bindings
.
.SH "Key bindings"
CTRL\-P go to the Previous command in your history CTRL\-N go to the Next command in your history CTRL\-R Reverse\-search through your history CTRL\-S Search forward through your history CTRL\-A Move the cursor to the beginning of the line CTRL\-E Move the cursor to the end of the line CTRL\-W delete a Word backwards ALT\-D delete a word forwards CTRL\-F move the cursor Forward 1 character CTRL\-B move the cursor Backward 1 character ALT\-F move the cursor Forward 1 word ALT\-B move the cursor Backward 1 word ALT\-_ undo
