.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BASH_CONDITIONS" "1" "July 2011" "" ""
.
.SH "NAME"
\fBbash_conditions\fR
.
.P
bash(1) \-\- Conditional statments
.
.SH "LINKS"
\fIhttp://www\.linuxtutorialblog\.com/post/tutorial\-conditions\-in\-bash\-scripting\-if\-statements\fR
