.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DEBIAN_BUILD_PACKAGES" "1" "April 2011" "" ""
.
.SH "DESCRIPTION"
\fB$ mkdir \-p \./debian/usr/bin\fR \fB$ cp linuxstatus \./debian/usr/bin\fR
.
.P
The version number must have a dash with an additional Debian package version number, e\.g\. \'1\.1\-1\'\. If your program consists e\.g\. only of portable shell scripts, use \'all\' as its \'Architecture\'\.
.
.P
For \'Depends\' you might need to find out to which package a certain file or program your new package relies onto belongs to\. You can use \'dpkg \-S \fIfile\fR\' for this to find this out, e\.g\.:
.
.P
\fB$ dkpg \-S /bin/cat\fR
.
.P
Then to find out more about package \'coreutils\' you can use the command \'apt\-cache showpkg coreutils\', which will tell you among other things the current version number that is installed on the system\.
.
.P
As a side note, there are two more ways to find the same information\. There is a web page where you can search for Debian files: http://www\.debian\.org/distrib/packages\. Go to the bottom of that page to fill out the web form\.
.
.P
Last not least there is a nice GUI application named \'kpackage\', which provides convenient package browsing options and also allows to search after packages given individual file names\.
.
.P
\'Suggests\', \'Conflicts\', and \'Replaces\' etc\. can be left out if not needed\.
.
.P
So here is the result of our first \'control\' file:
.
.IP "" 4
.
.nf

Package: linuxstatus
Version: 1\.1\-1
Section: base
Priority: optional
Architecture: all
Depends: bash (>= 2\.05a\-11), textutils (>= 2\.0\-12), awk, procps (>= \e
1:2\.0\.7\-8), sed (>= 3\.02\-8), grep (>= 2\.4\.2\-3), coreutils (>= 5\.0\-5)
Maintainer: Chr\. Clemens Lee <clemens@kclee\.de>
Description: Linux system information
 This script provides a broad overview of different
 system aspects\.
.
.fi
.
.IP "" 0
.
.P
The \'control\' file gets copied into a directory called \'DEBIAN\' inside the other \'debian\' directory\.
.
.P
\fB$ mkdir \-p debian/DEBIAN\fR
.
.IP "" 4
.
.nf

# this is necessary on Debian Woody, don\'t ask me why
.
.fi
.
.IP "" 0
.
.P
\fB$ find \./debian \-type d | xargs chmod 755\fR \fB$ cp control debian/DEBIAN\fR
.
.P
Now it is almost done\. Just type:
.
.P
\fB$ dpkg\-deb \-\-build debian\fR
.
.P
dpkg\-deb: building package \fBlinuxstatus\' in\fRdebian\.deb\'\.
.
.P
\fB$ mv debian\.deb linuxstatus_1\.1\-1_all\.deb\fR
.
.P
Now we just have to install this package on our box and we are done:
.
.P
\fB# dpkg \-i \./linuxstatus_1\.1\-1_all\.deb\fR
.
.P
Type \'linuxstatus\' or \'ls \-l /usr/bin/linuxstatus\' to see if it worked\. If you don\'t like your package any more, just type \'dpkg \-r linuxstatus\' and check again that the package is deinstalled\. If you install a newer version you don\'t have to remove the old one first, thought\.
.
.SS "Double Check \- lintian"
If you have not installed it yet on your system, this is a good moment (apt\-get install lintian)\.
.
.P
Now we use this little treasure tool on our new package file:
.
.IP "" 4
.
.nf

`$ lintian linuxstatus_1\.1\-1_all\.deb`
E: linuxstatus: binary\-without\-manpage linuxstatus
E: linuxstatus: no\-copyright\-file
W: linuxstatus: prerm\-does\-not\-remove\-usr\-doc\-link
W: linuxstatus: postinst\-does\-not\-set\-usr\-doc\-link
.
.fi
.
.IP "" 0
.
.SH "Links"
\fIhttp://tldp\.org/HOWTO/html_single/Debian\-Binary\-Package\-Building\-HOWTO\fR
.
.SH "SEE ALSO"
dpkg(5), lintian(5), man(1)
