.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EMACS" "1" "August 2011" "" ""
.
.SH "NAME"
\fBemacs\fR \- Replace regexp
.
.SH "EXAMPLES"
.
.nf

 M\-x replace\-regexp <RET> c[ad]+r <RET> \e&\-safe <RET>

 M\-x replace\-regexp <RET> \e(c[ad]+r\e)\-safe <RET> \e1 <RET>

 [\-+[:digit:]]                     digit or + or \- sign
 \e(\e+\e|\-\e)?[0\-9]+\e(\e\.[0\-9]+\e)?     decimal number (\-2 or 1\.5 but not \.2 or 1\.)
 \e(\ew+\e) +\e1\e>                     two consecutive, identical words
 \e<[[:upper:]]\ew*                  word starting with an uppercase letter
  +$                               trailing whitespaces (note the starting SPC)
 \ew\e{20,\e}                         word with 20 letters or more
 \ew+phony\e>                        word ending by phony
 \e(19\e|20\e)[0\-9]\e{2\e}              year 1900\-2099
 ^\.\e{6,\e}                          at least 6 symbols
 ^[a\-zA\-Z0\-9_]\e{3,16\e}$            decent string for a user name
 <tag[^> C\-q C\-j ]*>\e(\.*?\e)</tag>  html tag
.
.fi
.
.SH "First line in buffer"
.
.nf

 M\-x replace\-regexp <RET> ^ <RET> whatever <RET>
.
.fi
.
.SH "Repeating our example to exchange ‘x’ and ‘y’, we can thus do it also this way:"
.
.nf

 M\-x replace\-regexp <RET> \e(x\e)\e|y <RET>
 \e,(if \e1 "y" "x") <RET>
.
.fi
.
.SH "For computing replacement strings for ‘\e,’, the format function is often"
.
.SH "useful (see Formatting Strings)\. For example, to add consecutively"
.
.SH "numbered strings like ‘ABC00042’ to columns 73 to 80 (unless they are"
.
.SH "already occupied), you can use"
.
.nf

M\-x replace\-regexp <RET> ^\.\e{0,72\e}$ <RET>
 \e,(format "%\-72sABC%05d" \e& \e#) <RET>
.
.fi
.
.SH "TIPS"
.
.nf

M\-x re\-builder
.
.fi
.
.SH "LINKS"
.
.IP "\(bu" 4
\fIhttp://www\.gnu\.org/software/emacs/manual/html_node/emacs/Regexp\-Replace\.html\fR
.
.IP "\(bu" 4
\fIhttp://www\.gnu\.org/software/emacs/manual/html_node/elisp/Formatting\-Strings\.html\fR
.
.IP "\(bu" 4
\fIhttp://www\.gnu\.org/software/emacs/elisp/html_node/Regexp\-Search\.html\fR
.
.IP "\(bu" 4
\fIhttp://emacsblog\.org/2007/03/15/newbie\-tip\-re\-builder/\fR
.
.IP "" 0

