.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "EMACS" "1" "August 2011" "" ""
.
.SH "From ruby\-mode\.el"
\fBM\-C\-a\fR Beginning of defun
.
.br
\fBM\-C\-e\fR End of defun
.
.br
\fBM\-C\-b or M\-C\-p\fR Beginning of block
.
.br
\fBM\-C\-f or M\-C\-n\fR End of block
.
.br
\fBM\-C\-h\fR Mark defun
.
.br
\fB\et\fR Indent
.
.br
\fBC\-c C\-e\fR Insert end
.
.br
\fBC\-j\fR Reindent then newline and indent
.
.br
\fBC\-m\fR Newline
.
.br
.
.SH "From inf\-ruby\.el"
\fBC\-c C\-e or M\-C\-x\fR send the current definition to the process buffer
.
.br
\fBC\-c M\-e\fR switch to ruby process buffer after sending their text
.
.br
\fBC\-c C\-r\fR send the current region to the process buffer
.
.br
\fBC\-c M\-r\fR switch to ruby process buffer after sending their text
.
.br
\fBC\-c C\-z\fR switches the current buffer to the ruby process buffer
.
.br
\fBC\-c C\-l\fR Load a Ruby file into the inferior Ruby process\.
.
.br
\fBC\-c C\-s or M\-x run\-ruby\fR Run an inferior Ruby process\.\.\.
.
.br
.
.SH "TIPS"
Emacs opens in yaml\-mode and outdent\-mode when first line is:
.
.br
\fB# \-*\- mode: yaml; mode: outdent; \-*\-\fR
.
.P
To open a file in emacs on a specific line use the following command: \fBemacs +<no> <file>\fR
.
.P
For more: \fIhttp://wiki\.rubyonrails\.org/rails/pages/HowToUseEmacsWithRails\fR
