.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FILES_COMMANDS" "1" "September 2011" "" ""
.
.SH "Directories:"
File and directory paths in UNIX use the forward slash "/" to separate directory names in a path\.
.
.P
examples:
.
.P
/ "root" directory /usr directory usr (sub\-directory of / "root" directory) /usr/STRIM100 STRIM100 is a subdirectory of /usr
.
.P
Moving around the file system:
.
.P
pwd Show the "present working directory", or current directory\. cd Change current directory to your HOME directory\. cd /usr/STRIM100 Change current directory to /usr/STRIM100\. cd INIT Change current directory to INIT which is a sub\-directory of the current
.
.IP "" 4
.
.nf

                    directory\.
.
.fi
.
.IP "" 0
.
.P
cd \.\. Change current directory to the parent directory of the current directory\. cd $STRMWORK Change current directory to the directory defined by the environment
.
.IP "" 4
.
.nf

                    variable \'STRMWORK\'\.
.
.fi
.
.IP "" 0
.
.P
cd ~bob Change the current directory to the user bob\'s home directory (if you have permission)\.
.
.SH "Listing directory contents:"
ls list a directory ls \-l list a directory in long ( detailed ) format
.
.P
for example: $ ls \-l drwxr\-xr\-x 4 cliff user 1024 Jun 18 09:40 WAITRON_EARNINGS \-rw\-r\-\-r\-\- 1 cliff user 767392 Jun 6 14:28 scanlib\.tar\.gz ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ | | | | | | | | | | | | | | | | owner group size date time name | | | | number of links to file or directory contents | | | permissions for world | | permissions for members of group | permissions for owner of file: r = read, w = write, x = execute \-=no permission type of file: \- = normal file, d=directory, l = symbolic link, and others\.\.\.
.
.P
ls \-a List the current directory including hidden files\. Hidden files start
.
.IP "" 4
.
.nf

         with "\."
.
.fi
.
.IP "" 0
.
.P
ls \-ld * List all the file and directory names in the current directory using
.
.IP "" 4
.
.nf

         long format\. Without the "d" option, ls would list the contents
         of any sub\-directory of the current\. With the "d" option, ls
         just lists them like regular files\.
.
.fi
.
.IP "" 0
.
.SH "Changing file permissions and attributes"
chmod 755 file Changes the permissions of file to be rwx for the owner, and rx for
.
.IP "" 4
.
.nf

                 the group and the world\. (7 = rwx = 111 binary\. 5 = r\-x = 101 binary)
.
.fi
.
.IP "" 0
.
.P
chgrp user file Makes file belong to the group user\. chown cliff file Makes cliff the owner of file\. chown \-R cliff dir Makes cliff the owner of dir and everything in its directory tree\.
.
.P
You must be the owner of the file/directory or be root before you can do any of these things\.
.
.SH "Moving, renaming, and copying files:"
cp file1 file2 copy a file mv file1 newname move or rename a file mv file1 ~/AAA/ move file1 into sub\-directory AAA in your home directory\. rm file1 [file2 \.\.\.] remove or delete a file rm \-r dir1 [dir2\.\.\.] recursivly remove a directory and its contents BE CAREFUL! mkdir dir1 [dir2\.\.\.] create directories mkdir \-p dirpath create the directory dirpath, including all implied directories in the path\. rmdir dir1 [dir2\.\.\.] remove an empty directory
.
.SH "Viewing and editing files:"
cat filename Dump a file to the screen in ascii\. more filename Progressively dump a file to the screen: ENTER = one line down
.
.IP "" 4
.
.nf

              SPACEBAR = page down  q=quit
.
.fi
.
.IP "" 0
.
.P
less filename Like more, but you can use Page\-Up too\. Not on all systems\. vi filename Edit a file using the vi editor\. All UNIX systems will have vi in some form\. emacs filename Edit a file using the emacs editor\. Not all systems will have emacs\. head filename Show the first few lines of a file\. head \-n filename Show the first n lines of a file\. tail filename Show the last few lines of a file\. tail \-n filename Show the last n lines of a file\.
.
.SH "Command Substitution"
You can use the output of one command as an input to another command in another way called command substitution\. Command substitution is invoked when by enclosing the substituted command in backwards single quotes\. For example:
.
.P
cat \fBfind \. \-name aaa\.txt\fR
.
.P
which will cat ( dump to the screen ) all the files named aaa\.txt that exist in the current directory or in any subdirectory tree\.
.
.P
Searching for strings in files: The grep command
.
.P
grep string filename prints all the lines in a file that contain the string
.
.P
Searching for files : The find command
.
.P
find search_path \-name filename
.
.P
find \. \-name aaa\.txt Finds all the files named aaa\.txt in the current directory or
.
.IP "" 4
.
.nf

                    any subdirectory tree\.
.
.fi
.
.IP "" 0
.
.P
find / \-name vimrc Find all the files named \'vimrc\' anywhere on the system\. find /usr/local/games \-name "\fIxpilot\fR"
.
.IP "" 4
.
.nf

                    Find all files whose names contain the string \'xpilot\' which
                    exist within the \'/usr/local/games\' directory tree\.
.
.fi
.
.IP "" 0
.
.SH "Reading and writing tapes, backups, and archives: The tar command"
The tar command stands for "tape archive"\. It is the "standard" way to read and write archives (collections of files and whole directory trees)\.
.
.P
Often you will find archives of stuff with names like stuff\.tar, or stuff\.tar\.gz\. This is stuff in a tar archive, and stuff in a tar archive which has been compressed using the gzip compression program respectivly\.
.
.P
Chances are that if someone gives you a tape written on a UNIX system, it will be in tar format, and you will use tar (and your tape drive) to read it\.
.
.P
Likewise, if you want to write a tape to give to someone else, you should probably use tar as well\.
.
.P
Tar examples:
.
.P
tar xv Extracts (x) files from the default tape drive while listing (v = verbose)
.
.IP "" 4
.
.nf

        the file names to the screen\.
.
.fi
.
.IP "" 0
.
.P
tar tv Lists the files from the default tape device without extracting them\. tar cv file1 file2
.
.IP "" 4
.
.nf

        Write files \'file1\' and \'file2\' to the default tape device\.
.
.fi
.
.IP "" 0
.
.P
tar cvf archive\.tar file1 [file2\.\.\.]
.
.IP "" 4
.
.nf

        Create a tar archive as a file "archive\.tar" containing file1,
        file2\.\.\.etc\.
.
.fi
.
.IP "" 0
.
.P
tar xvf archive\.tar extract from the archive file tar cvfz archive\.tar\.gz dname
.
.IP "" 4
.
.nf

        Create a gzip compressed tar archive containing everything in the directory
        \'dname\'\. This does not work with all versions of tar\.
.
.fi
.
.IP "" 0
.
.P
tar xvfz archive\.tar\.gz
.
.IP "" 4
.
.nf

        Extract a gzip compressed tar archive\.  Does not work with all versions of tar\.
.
.fi
.
.IP "" 0
.
.P
tar cvfI archive\.tar\.bz2 dname
.
.IP "" 4
.
.nf

        Create a bz2 compressed tar archive\. Does not work with all versions of tar
.
.fi
.
.IP "" 0
.
.SH "File compression: compress, gzip, and bzip2"
The standard UNIX compression commands are compress and uncompress\. Compressed files have a suffix \.Z added to their name\. For example:
.
.P
compress part\.igs Creates a compressed file part\.igs\.Z
.
.P
uncompress part\.igs Uncompresseis part\.igs from the compressed file part\.igs\.Z\.
.
.IP "" 4
.
.nf

                 Note the \.Z is not required\.
.
.fi
.
.IP "" 0
.
.P
Another common compression utility is gzip (and gunzip)\. These are the GNU compress and uncompress utilities\. gzip usually gives better compression than standard compress, but may not be installed on all systems\. The suffix for gzipped files is \.gz
.
.P
gzip part\.igs Creates a compressed file part\.igs\.gz gunzip part\.igs Extracts the original file from part\.igs\.gz
.
.P
The bzip2 utility has (in general) even better compression than gzip, but at the cost of longer times to compress and uncompress the files\. It is not as common a utility as gzip, but is becoming more generally available\.
.
.P
bzip2 part\.igs Create a compressed Iges file part\.igs\.bz2 bunzip2 part\.igs\.bz2 Uncompress the compressed iges file\.
