.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NGINX" "1" "July 2011" "" ""
.
.SH "NAME"
\fBnginx\fR \- cheat sheet
.
.SH "Installation"
Install passenger as instructed in rvm documentation http://rvm\.beginrescueend\.com/integration/passenger/
.
.IP "" 4
.
.nf

rvm 1\.9\.2 \-\-passenger
rvm 1\.9\.2
gem install passenger
rvmsudo passenger\-install\-nginx\-module
.
.fi
.
.IP "" 0
.
.SH "LINKS"
\fIhttp://blog\.peepcode\.com/tutorials/2010/nginx\-passenger\-script\fR \fIhttp://freelancing\-gods\.com/posts/script_nginx\fR \fIhttp://www\.modrails\.com/documentation/Users%20guide%20Nginx\.html\fR
