.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONSOLE" "1" "May 2011" "" ""
.
.SH "NAME"
\fBconsole\fR \- cheat sheets
.
.SH "Controller Actions"
.
.nf

app\.get(\'sample/echo\')
output = app\.html_document\.root\.to_s
.
.fi
.
.SH "Put it into a rake task"
.
.nf

require \'action_controller/integration\'

namespace :actions do
desc "test action"
  task "echo" do
    app = ActionController::Integration::Session\.new;
    app\.get(\'/sample/echo\')
    puts app\.html_document\.root\.to_s
  end
end
.
.fi
.
.P
Call it with:
.
.IP "" 4
.
.nf

 rake actions:echo
.
.fi
.
.IP "" 0

