.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RCS" "1" "July 2011" "" ""
.
.SH "NAME"
\fBrcs\fR \- cheat sheet
.
.SH "create the baseline:"
\fBci <filename>\fR is the RCS command to "check in" a file It creates and/or writes to a file named filename,v where filename is the name of the file being checked in\. There is a separate RCS baseline *,v file created for each file that is checked in\. Note: that when ci checked the file into the baseline ,v file, it got rid of the original source code file\.
.
.IP "" 4
.
.nf

ci file_name
.
.fi
.
.IP "" 0
.
.P
\fBco <filename>\fR checks a file out of an RCS baseline for any purpose\. This basic use of co checks it out in shared, or "unlocked" mode\. to check the file out locked so that you can make changes to it\.
.
.IP "" 4
.
.nf

co \-l file_name
.
.fi
.
.IP "" 0
.
.P
When you check a modified file in, ci will by default automatically create a new revision number by incrementing the file\'s last level number by one\. In this example, checking in the modified helloworld\.c 1\.1 creates revision 1\.2\. To set the new revision number of a checked in file to something other than the default, use the \-r option, such as:
.
.IP "" 4
.
.nf

ci \-r2\.1 file_name
.
.fi
.
.IP "" 0
.
.P
to assign 2\.1 instead of 1\.2 as the number of the new revision\.
