.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_COLORED" "1" "March 2011" "" ""
.
.SH "Examples:"
.
.nf

>> puts "this is red"\.red

>> puts "this is red with a blue background (read: ugly)"\.red_on_blue

>> puts "this is red with an underline"\.red\.underline

>> puts "this is really bold and really blue"\.bold\.blue

>> logger\.debug "hey this is broken!"\.red_on_yellow     # in rails

>> puts Color\.red "This is red" # but this part is mostly untested
.
.fi

