.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_AMBITION" "1" "March 2011" "" ""
.
.SH "Query#to_sql"
.
.nf

>> User\.select { |m| m\.name == \'jon\' }\.to_sql
=> "SELECT * FROM users WHERE users\.name = \'jon\'"
.
.fi
.
.SH "Query#to_hash"
.
.nf

>> User\.select { |m| m\.name == \'jon\' }\.to_hash
=> {:conditions=>"users\.name = \'jon\'"}
.
.fi
.
.SH "Equality"
.
.nf

User\.select { |m| m\.name == \'jon\' }
User\.select { |m| m\.name != \'jon\' }
User\.select { |m| m\.name == \'jon\' && m\.age == 21 }
User\.select { |m| (m\.name == \'jon\' || m\.name == \'rick\') && m\.age == 21 }
.
.fi
.
.SH "Associations"
.
.nf

User\.select { |u| u\.email == \'chris@ozmm\.org\' && u\.profile\.name == \'chris wanstrath\' }\.map(&:title)
.
.fi
.
.SH "Comparisons"
.
.nf

User\.select { |m| m\.age < 21 }\.to_sql
User\.select { |m| [1, 2, 3, 4]\.include? m\.id }
.
.fi
.
.SH "LIKE and REGEXP"
.
.nf

User\.select { |m| m\.name =~ \'chri%\' }
User\.select { |m| m\.name !~ \'chris\' }
User\.select { |m| !(m\.name =~ \'chris\') }
User\.select { |m| m\.name =~ /chris/ }
.
.fi
.
.SH "Detect"
.
.nf

User\.detect { |m| m\.name == \'chris\' }
.
.fi
.
.SH "Limits"
.
.nf

User\.select { |m| m\.name == \'jon\' }\.first
User\.select { |m| m\.name == \'jon\' }\.first(5)
User\.select { |m| m\.name == \'jon\' }[10, 20]
User\.select { |m| m\.name == \'jon\' }[10\.\.20]
.
.fi
.
.SH "Sort"
.
.nf

User\.select { |m| m\.name == \'jon\' }\.sort_by { |m| m\.name }
User\.select { |m| m\.name == \'jon\' }\.sort_by { |m| [ m\.name,  \-m\.age ] }
User\.select { |m| m\.name == \'jon\' }\.sort_by { |m| \-m\.profiles\.title }
User\.select { |m| m\.name == \'jon\' }\.sort_by { rand }
.
.fi
.
.SH "Count"
.
.nf

User\.select { |m| m\.name == \'jon\' }\.size
.
.fi
.
.SH "Other"
.
.nf

User\.any? { |m| m\.name == \'jon\' }
User\.all? { |m| m\.name == \'jon\' }
User\.select { |m| m\.name == \'jon\' }\.empty?
User\.select { |m| m\.name\.downcase =~ \'jon%\' }\.to_sql
.
.fi

