.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_OPERATORS" "1" "March 2011" "" ""
.
.SH "list"
.
.nf

:: \.
[]
**
\-(unary) +(unary) ! ~
*  /  %
+  \-
<<  >>
&
|  ^
>  >=  <  <=
<=> == === != =~ !~
&&
||
\.\. \.\.\.
=(+=, \-=\.\.\.)
not
and or
.
.fi
.
.SH "Non\-methods"
=, ::, \., \.\., \.\.\., !, not, &&, and, ||, or, !=, !~
.
.P
In addition, assignment operators(+= etc\.) are not user\-definable\.
