.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_STRING" "1" "April 2011" "" ""
.
.SH "Delimiters:"
.
.nf

\'singlequote\'    "doublequote"
%q/single/       %Q!double!
%q<single>       %Q(double)
                 %{double}
.
.fi
.
.SH "Escapes (double\-quote):"
.
.nf

|\-\-\-\-+\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-|
| E  | ASC | Name(s)             |  Hex | Dec |
|\-\-\-\-+\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-|
| \ea | BEL | bell, alert         | 0x07 |   7 |
| \eb | BS  | backspace           | 0x08 |   8 |
| \ee | ESC | escape              | 0x1b |  27 |
| \ef | NP  | formfeed, newpage   | 0x0c |  12 |
| \en | NL  | linefeed, newline   | 0x0a |  10 |
| \er | CR  | carriage return     | 0x0d |  13 |
| \es | SP  | space               | 0x20 |  32 |
| \et | HT  | tab, horizontal tab | 0x09 |   9 |
| \ev | VT  | vertical tab        | 0x0b |  11 |
|\-\-\-\-+\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-|

|\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
| Format  | Translation      |
|\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
| \ennn    | Octal nnn        |
| \exnn    | Hexadecimal 0xnn |
| \ecx     | Control\-x        |   Control\-x == (?x & 0b10011111)
| \eC\-x    | Control\-x        |
| \eM\-x    | Meta\-x           |   Meta\-x == (?x | 0b10000000)
| \eM\-\eC\-x | Meta\-control\-x   |
| \ex      | x                |
| #{expr} | Value of expr    |
|\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
.
.fi
.
.SH "Escapes (single\-quote)"
.
.nf

|\-\-\-\-+\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-|
| E  | ASC | Name         |  Hex | Dec |
|\-\-\-\-+\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-|
| \e\' | \'   | single\-quote | 0x27 |  39 |
| \e\e | \e   | backslash    | 0x5c |  92 |
|\-\-\-\-+\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-+\-\-\-\-\-|
.
.fi

