.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_RAILS_MIGRATIONS" "1" "April 2011" "" ""
.
.SH "valid data types:"
.
.nf

  :integer :float
  :datetime :date :timestamp :time
  :text :string
  :binary
  :boolean
.
.fi
.
.SH "options:"
.
.nf

  :null (boolean)
  :limit (integer)
  :default
  :precision (integer)
  :scale (integer)
.
.fi
.
.P
create the model \fB\./script/generate model model_name\fR apply schema changes \fBrake db:migrate\fR modify schema \fB\./script generate migration description_name\fR
.
.P
\fIhttp://wiki\.rubyonrails\.com/rails/pages/UsingMigrations\fR
