.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_RAILS_REST" "1" "July 2011" "" ""
.
.SH "Resource Routes (in config/routes\.rb)"
Simple
.
.br
.
.IP "" 4
.
.nf

map\.resources :users, :sessions
.
.fi
.
.IP "" 0
.
.P
Nested
.
.br
.
.IP "" 4
.
.nf

map\.resources :teams do |teams|
  teams\.resources :players
end
.
.fi
.
.IP "" 0
.
.P
Customized
.
.br
.
.IP "" 4
.
.nf

map\.resources :articles,
              :collection  => {:sort => :put},
              :member      => {:deactivate => :delete},
              :new         => {:preview => :post},
              :controller  => \'articles\',
              :singular    => \'article\',
              :path_prefix => \'/book/:book_id\',
              :name_prefix => \'book_\'
.
.fi
.
.IP "" 0
.
.P
Including the default route (/:controller/:action/:id) will allow any verb to access any action\. This is usually not what you want, so you should probably delete it from routes\.rb
.
.br
.
.IP "" 4
.
.nf

| Standard Methods       | Verb   | Path          | Action  |
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-|
|       plural_path      | GET    | /teams        | index   |
|     singular_path(id)  | GET    | /teams/1      | show    |
| new_singular_path      | GET    | /teams/new    | new     |
|       plural_path      | POST   | /teams        | create  |
| edit_singular_path(id) | GET    | /teams/1;edit | edit    |
|      singular_path(id) | PUT    | /teams/1      | update  |
|      singular_path(id) | DELETE | /teams/1      | destroy |
.
.fi
.
.IP "" 0
.
.P
Each method also has a counterpart ending in \fIurl that includes the protocol, domain, and port\. There is also a hash_for\fR version of each method that returns a hash instead of a string\.
.
.br
.
.IP "" 4
.
.nf

| Formats in the URL                         | Path                  |
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
| formatted_plural_path(:xml)                | /teams\.xml            |
| formatted_singular_path(id, :rss)          | /teams\.1\.rss          |
| formatted_players_path(@team, :atom)       | /teams/1/players\.atom |
| formatted_player_path(@team, @player, :js) | /teams/1/players/5\.js |
| formatted_player_path(:team_id => 1,       | /teams/1/players/5\.js |
|               id => 5, :format => :js)     |                       |
.
.fi
.
.IP "" 0
.
.P
Any URL\-generating method can take a hash of options instead of bare arguments\. This is the only way to generate a URL with extra querystring params\.
.
.br
.
.SH "button_to \"Destroy\","
.
.nf

      team_path(@team),
      :confirm => "Are you sure?",
      :method => :delete
.
.fi
.
.SH "link_to \"Destroy\","
.
.nf

    team_path(@team),
    :confirm => "Are you sure?",
    :method => :delete
.
.fi
.
.SH "link_to_remote \"Destroy\","
.
.nf

           :url => team_path(@team),
           :confirm => "Are you sure?",
           :method => :delete
.
.fi
.
.SH "form_for :team,"
.
.nf

     @team,
     :url => team_path(@team),
     :html => {
       :method => :put
     } do |f| \.\.\.

| Nested Resources            | Path                        |
|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
| players_path(@team)         | /teams/:team_id/players     |
|                             | /teams/1/players            |
| player_path(@team, @player) | /teams/:team_id/players/:id |
|                             | /teams/1/players/5          |
.
.fi
.
.P
Nested resources must be defined in routes\.rb\. See above for an example\.
.
.br
.
.SH "Useful Plugins"
Beast Forum (an app built with RESTful design)
.
.br
.
.IP "" 4
.
.nf

http://svn\.techno\-weenie\.net/projects/beast/trunk/
.
.fi
.
.IP "" 0
.
.P
RESTFUL Authentication Plugin
.
.br
.
.IP "" 4
.
.nf

http://svn\.techno\-weenie\.net/projects/plugins/restful_authentication/
.
.fi
.
.IP "" 0
.
.P
Simply Helpful Plugin<>br
.
.IP "" 4
.
.nf

http://dev\.rubyonrails\.org/svn/rails/plugins/simply_helpful/

respond_to { |wants|
  wants\.all | \.text | \.html | \.js | \.ics | \.xml | \.rss | \.atom | \.yaml
}

Add New MIME types (in config/initializers/mime\.rb)
  Mime::Type\.register "image/jpg", :jpg
  Mime::Type\.register "application/vnd\.visa+xml", :visa
.
.fi
.
.IP "" 0
.
.P
Types listed here can be used in a respond_to block and as a forced format extension at the end of urls\.
.
.br
.
.SH "Scaffold Resource Generator"
.
.nf

\&\./script/generate scaffold
                  Episode
                  title:string
                  description:text
                  program_id:integer
.
.fi
.
.P
Use a singular word for the model/resource name\. The other arguments will be used to pre\-populate the database migration and fields in view templates\.
.
.P
Mostly from \fIhttp://peepcode\.com/articles/2006/10/08/restful\-rails\fR
