.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_RAILS_REFINERY" "1" "April 2011" "" ""
.
.SH "Basics"
After scratch install enable \fIpage parts\fR by setting the \fINew Page Parts\fR value to \fItrue\fR
.
.SH "Links"
\fIhttp://refinerycms\.com/guides/how\-to\-change\-page\-parts\fR
