.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_RAILS_CONSOLE" "1" "July 2011" "" ""
.
.SH "Reloading the Console Environment:"
.
.nf

>> reload!
>> Dispatcher\.reset_application!   # (outdated)
.
.fi
.
.SH "Load and execute a Ruby script:"
.
.nf

>> load "the_file_name\.rb"
.
.fi
.
.SH "Using app object:"
.
.nf

>> app\.get \'/stories/10002\'
=> 200
>> app\.assigns(:story)
=> #<Story:0x24aad0c \.\.\. >
>> app\.path
=> "/stories/10002"
>> app\.reset!
=> nil
.
.fi
.
.SH "Using helpers methods:"
.
.nf

>> helper\.pluralize 2, "story"
=> "2 stories"
.
.fi
.
.SH "Clear the console:"
.
.nf

ctrl + l or Command + k (Mac)
.
.fi
.
.SH "How\-to Examine Routes:"
.
.nf

rs = ActionController::Routing::Routes
puts rs\.routes
rs\.recognize_path "/session"
rs\.generate :controller => "users", :action => "edit", :id => "4"
.
.fi
.
.SH "Print as YAML"
.
.nf

>> y @something
.
.fi
.
.P
Start in a sandbox (any modifications you make to the database will be rolled back on exit)
.
.IP "" 4
.
.nf

$ \./script/console \-s
.
.fi
.
.IP "" 0

