.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CACHING" "1" "July 2011" "" ""
.
.SH "NAME"
\fBcaching\fR \- cheat sheet
.
.SH "in my heroku console"
.
.nf

ActionController::Base\.cache_store\.clear
.
.fi
.
.SH "LINKS"
\fIhttp://ror\.kateray\.net/post/1373868975/scaling\-1\-caching\-with\-heroku\fR
