.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_RDOC" "1" "March 2011" "" ""
.
.SH "Lists:"
.
.nf

* This is a list element
\- This is one too\.
1\. This one will be numbered
[word] description
word:: description
.
.fi
.
.SH "Styling:"
.
.nf

_italic_::     \e_word_ or \e<em>text</em>
*bold*::       \e*word* or \e<b>text</b>
+typewriter+:: \e+word+ or \e<tt>text</tt>
= Level One Heading
== Level Two Heading
.
.fi
.
.SH ":title:text Sets the title for the document\."

