.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_RAILS_TO_S" "1" "April 2011" "" ""
.
.nf

>> 3\.days\.ago\.to_s(:db)
.
.fi
.
.SH "Formats:"
\fB:db\fR
.
.IP "" 4
.
.nf

"%Y\-%m\-%d %H:%M:%S" (ie: "2006\-12\-04 19:00:26")
.
.fi
.
.IP "" 0
.
.P
\fB:long\fR
.
.IP "" 4
.
.nf

"%B %d, %Y %H:%M" (ie: "December 04, 2006 19:00")
.
.fi
.
.IP "" 0
.
.P
\fB:rfc822\fR
.
.IP "" 4
.
.nf

"%a, %d %b %Y %H:%M:%S %z" (ie: "Mon, 04 Dec 2006 19:00:26 \-0700")
.
.fi
.
.IP "" 0
.
.P
\fB:short\fR
.
.IP "" 4
.
.nf

"%d %b %H:%M" (ie: "04 Dec 19:00")
.
.fi
.
.IP "" 0
.
.P
\fB:time\fR
.
.IP "" 4
.
.nf

"%H:%M" (ie: "19:00")
.
.fi
.
.IP "" 0
.
.SH "Add your own:"
.
.nf

Time::DATE_FORMATS[:mine] = \'%Y%m%d%M%S\'
 >> Time\.new\.to_s(:mine)
 => "200612040026"
.
.fi

