.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BUNDLER" "1" "July 2011" "" ""
.
.SH "NAME"
\fBbundler\fR \- cheat sheet
.
.SH "NOTE: Gem::Specification#default_executable="
consider \fBbundle exec\fR and \fBrvm use {ruby_with_broken_gem}\fR
.
.IP "" 4
.
.nf

gem pristine \-\-all \-\-no\-extensions
gem uninstall
.
.fi
.
.IP "" 0
.
.SH "use local gems in Gemfile"
.
.nf

gem "thin", :path => "local_gems/thin\-1\.2\.10/"
.
.fi

