.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_ACTS_AS_STATE_MACHINE" "1" "March 2011" "" ""
.
.SH "Example"
.
.nf

class Order < ActiveRecord::Base
  acts_as_state_machine :initial => :opened

  state :opened
  state :closed, :enter => Proc\.new {|o| Mailer\.send_notice(o)}
  state :returned

  event :close do
    transitions :to => :closed, :from => :opened
  end

  event :return do
    transitions :to => :returned, :from => :closed
  end
end

o = Order\.create
o\.close! # notice is sent by mailer
o\.return!
.
.fi

