.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_RAILS_REFINERY" "1" "April 2011" "" ""
.
.SH "Basics"
After scratch install enable \fIpage parts\fR by setting the \fINew Page Parts\fR value to \fItrue\fR
.
.SH "Rake Tasks"
.
.nf

rake refinery:override controller=what/ever
.
.fi
.
.SH "Pages"
\fBModel\fR
.
.P
Methods:
.
.TP
\fBnested_path()\fR
p\.nested_path "/path/to/page"
.
.SH "Links"
\fIhttp://refinerycms\.com/guides/how\-to\-change\-page\-parts\fR
