.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RUBY_EXCEPTIONS" "1" "July 2011" "" ""
.
.SH "Hierarchy"
.
.nf

Exception
 NoMemoryError
 ScriptError
   LoadError
   NotImplementedError
   SyntaxError
 SignalException
   Interrupt
 StandardError
   ArgumentError
   IOError
     EOFError
   IndexError
   LocalJumpError
   NameError
     NoMethodError
   RangeError
     FloatDomainError
   RegexpError
   RuntimeError
   SecurityError
   SystemCallError
   SystemStackError
   ThreadError
   TypeError
   ZeroDivisionError
 SystemExit
 fatal
.
.fi
.
.SH "Snippets"
.
.nf

  begin
    Rails\.cache\.delete_matched(/\.*whatever\.*/)
  rescue NotImplementedError
    warn "**** [whaterver] ***"
  end
.
.fi

