.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SASS" "1" "May 2011" "" ""
.
.SH "NAME"
\fBsass\fR \- cheat sheet
.
.SH "Rails/Heroku setup"
.
.nf

Compass\.configuration\.sass_options={:never_update=>true}
.
.fi
.
.SH "LINKS"
\fIhttp://blog\.danielfischer\.com/2011/04/18/quickstart\-guide\-to\-using\-compass\-haml\-sass\-scss\-with\-rails\-3/\fR \fIhttp://frontcube\.com/blog/2011/how\-to\-get\-sass\-to\-work\-with\-rails\-3\-on\-heroku\-without\-using\-any\-plugins\fR
